### ISSUE TITLE
Map::_freeArea segfault

### ISSUE THREAD

**Issue by elhmn** [JeanMax/nibbler#1]
Dans Map la fonction _freeArea segfault si _area == NULL. Tu devrais peut etre catcher ca au debut. je l'ai deja fait dans ma branche.

**Comment by JeanMax** [comment]
Yep c'est prevu de crash dans ce cas là. Pareil pour les *_players dans Game.
L'idée c'est que lancer un snake sans map ou sans joueur, ça va pas le faire.
Mais ouais faudrait que je balance une exception...

(je vois pas bien dans quel cas t'as pu faire ça, ya des limites sur les map trop grandes, donc ya assez peu de chances pour que la malloc foire)

**Comment by elhmn** [comment]
Nice 👍
